version: "3.7"

services:
    web:
        container_name: pagamentos_nginx
        build:
            context: ../
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/usr/share/nginx/html/
        depends_on:
            - php

    database:
        image: mysql:8
        container_name: pagamentos_mysql
        command: --default-authentication-plugin=mysql_native_password --sql_mode=''
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306

    php:
        build:
            context: ../
            dockerfile: ./docker/php/Dockerfile
        container_name: pagamentos_php
        ports:
            - 9000:9000
        volumes:
            - ../:/usr/share/nginx/html/
        depends_on:
            - database
            - redis

    redis:
        image: redis:latest
        container_name: pagamentos_redis
        ports:
            - 6379:6379

